Introduce namespace VectorTools
j507/RotatingMHD pull request #137
Opened 2021-08-16 14:28 UTC by sebglane

2021-08-16 14:29 UTC, sebglane commented
After #131

2021-08-16 14:29 UTC, sebglane commented
Fixes #129

2021-08-16 15:23 UTC, sebglane commented
@j507 Could you take a look at this before I replace all project, interpolate and compute error methods by the ones defined in the new namespace? This will make a review much simpler...

2021-08-16 19:11 UTC, j507 requested changes
Apart from the two comments, the `VectorTools` namespace and its contents looks clean and properly programmed.

2021-08-17 10:22 UTC, sebglane commented on include/rotatingMHD/data_postprocessors.h
> +    std::vector<Vector<double>> &computed_quantities) const override;
This method overloads [DataPostprocessor< dim >::evaluate_vector_field](https://dealii.org/9.2.0/doxygen/deal.II/classDataPostprocessor.html#a1ba57b598d24d64365d469a854271c68) which can compute all possible data from a vector-valued finite element solution. The name cannot be changed, but I will add some documentation.

2021-08-17 12:52 UTC, sebglane commented on include/rotatingMHD/data_postprocessors.h
> +  virtual UpdateFlags get_needed_update_flags() const override;
Fixed in PR #141

2021-08-19 07:47 UTC, sebglane commented
@j507 Do you think that this is ready to go? Should I run the DFG benchmark again?

2021-08-19 07:55 UTC, j507 approved these changes

2021-08-19 09:20 UTC, merged